### PR TITLE
Update Bindings for latest Upstream LDK

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by jkczyz** [comment]
Having difficulty running this on MacOS.

```bash
+ cd ..
+ mv lightning-c-bindings/src/c_types/mod.rs ./
+ mv lightning-c-bindings/src/bitcoin ./
+ git checkout lightning-c-bindings/src
+ git checkout lightning-c-bindings/include
++ git describe --tag --dirty
fatal: No names found, cannot describe anything.
+ BINDINGS_GIT=
```

**Comment by valentinewallace** [comment]
> Having difficulty running this on MacOS.
> 
> ```shell
> + cd ..
> + mv lightning-c-bindings/src/c_types/mod.rs ./
> + mv lightning-c-bindings/src/bitcoin ./
> + git checkout lightning-c-bindings/src
> + git checkout lightning-c-bindings/include
> ++ git describe --tag --dirty
> fatal: No names found, cannot describe anything.
> + BINDINGS_GIT=
> ```

Getting the same error on #25

**Comment by jkczyz** [comment]
Couple errors in `check_bindings` related to `EventHandler`:

```bash
error[E0053]: method `process_pending_events` has an incompatible type for trait
    --> src/lightning/util/events.rs:1125:2
     |
1125 |     fn process_pending_events<H:core::ops::Deref>(&self, mut handler: crate::lightning::util::events::EventHandler) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `H`, found struct `lightning::util::events::EventHandler`
     |
     = note: expected fn pointer `fn(&lightning::util::events::EventsProvider, H)`
                found fn pointer `fn(&lightning::util::events::EventsProvider, lightning::util::events::EventHandler)`

error[E0055]: reached the recursion limit while auto-dereferencing `lightning::util::events::EventHandler`
    --> src/lightning/util/events.rs:1126:56
     |
1126 |         (self.process_pending_events)(self.this_arg, handler.into())
     |                                                              ^^^^ deref recursion limit reached
     |
     = help: consider adding a `#![recursion_limit="256"]` attribute to your crate (`ldk`)

error: aborting due to 2 previous errors
```

**Comment by TheBlueMatt** [comment]
> fatal: No names found, cannot describe anything.

Huh, do you need `git fetch --tags`?

**Review by jkczyz — COMMENTED** [review]
> Huh, do you need `git fetch --tags`?

Same issue after running that.

**Comment by TheBlueMatt** [comment]
> Couple errors in check_bindings related to EventHandler:

Right, oops, just forgot to check in the latest bindings, should work with genbindings.

> git fetch --tags --all

Maybe `git fetch --tags --all`?

**Comment by jkczyz** [comment]
> Maybe `git fetch --tags --all`?

Yes, that worked.

**Review by jkczyz — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Squashed the fixup and re-bumped the git head. Will merge if CI passes:
```
$ git diff-tree -U1 71b69c5 123a003
diff --git a/lightning-c-bindings/Cargo.toml b/lightning-c-bindings/Cargo.toml
index c8e7c00..40d316e 100644
--- a/lightning-c-bindings/Cargo.toml
+++ b/lightning-c-bindings/Cargo.toml
@@ -20,5 +20,5 @@ secp256k1 = { version = "0.20.1", features = ["global-context-less-secure"] }
 # Note that the following line is matched by genbindings to update the path
-lightning = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "27c05fdd7f7ac8c485dbeb64a65215ce9deae0df", features = ["allow_wallclock_use"] }
-lightning-persister = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "27c05fdd7f7ac8c485dbeb64a65215ce9deae0df" }
-lightning-invoice = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "27c05fdd7f7ac8c485dbeb64a65215ce9deae0df" }
+lightning = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "3996eaab6e2eaf5fde9374b51d952c0edef5ea92", features = ["allow_wallclock_use"] }
+lightning-persister = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "3996eaab6e2eaf5fde9374b51d952c0edef5ea92" }
+lightning-invoice = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "3996eaab6e2eaf5fde9374b51d952c0edef5ea92" }
 
$
```

**Pull request merged**
