### PR TITLE
Update to handle Invoice generation and fix some issues

### PR DESCRIPTION
**Pull request by TheBlueMatt**

### CODE REVIEW

**Comment by jkczyz** [comment]
Not sure if it matters, but I'm seeing the following warning:

```term
In file included from demo.cpp:3:
./include/lightning.h:6571:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct LDKSignOrCreationError_LDKSignError_Body {
        ^
1 warning generated.
```

**Review by jkczyz — APPROVED** [review]

**Comment by TheBlueMatt** [comment]
Right, that warning is this: https://github.com/eqrion/cbindgen/issues/684. Its not a big deal since the other union member is non-0-size, but I went ahead and pushed a commit to convert such variants to non-tuple form (and ripped the relevant bits out of the "Drop stale () -> u8 mapping" commit.

**Review by jkczyz — APPROVED** [review]
ACK bc896ae8a67f7af0613a137a727f2873b9e76f7d

**Comment by TheBlueMatt** [comment]
Updated the git hashes to upstream now that the dependent PR has been merged. Will take after CI.

```
$ git diff-tree -U1 bc896ae d89a817
diff --git a/lightning-c-bindings/Cargo.toml b/lightning-c-bindings/Cargo.toml
index ae8d174..badaf9f 100644
--- a/lightning-c-bindings/Cargo.toml
+++ b/lightning-c-bindings/Cargo.toml
@@ -20,5 +20,5 @@ secp256k1 = { version = "0.20.1", features = ["global-context-less-secure"] }
 # Note that the following line is matched by genbindings to update the path
-lightning = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "e4f55b71f770864a3a139e5af01210b526f62d91", features = ["allow_wallclock_use"] }
-lightning-persister = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "e4f55b71f770864a3a139e5af01210b526f62d91" }
-lightning-invoice = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "e4f55b71f770864a3a139e5af01210b526f62d91" }
+lightning = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "d4d322580994857b1222488f8467311d6db61482", features = ["allow_wallclock_use"] }
+lightning-persister = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "d4d322580994857b1222488f8467311d6db61482" }
+lightning-invoice = { git = "https://git.bitcoin.ninja/rust-lightning", rev = "d4d322580994857b1222488f8467311d6db61482" }
```

**Pull request merged**
