### PR TITLE
LDK 0.0.116

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Depends on https://github.com/lightningdevkit/rust-lightning/pull/2443

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
Upstream bindings PR landed, so this should be good to go. CI should pass now.

**Comment by tnull** [comment]
> Upstream bindings PR landed, so this should be good to go. CI should pass now.

... or proc-macro2 needs some pinning here 🥲 :

```
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

(edit) Ah, nvm.

**Comment by TheBlueMatt** [comment]
Heh, just pushed.

**Comment by tnull** [comment]
> Heh, just pushed.

Yo dawg I heard you like pinning? So I put a `quote` in your `proc-macro2` so you can pin while you pin.

**Comment by TheBlueMatt** [comment]
Ugh.

**Comment by TheBlueMatt** [comment]
Dug into the root cause on the segfault on OSX, was an aliasing violation, I fixed it should be good now.

**Comment by TheBlueMatt** [comment]
Rebased after the 115.3 release.

**Comment by TheBlueMatt** [comment]
Oops, forgot to check in new auto-generated files, fixed now.

**Comment by TheBlueMatt** [comment]
Added one more commit for Java, which I've now done full binaries and tests for, CI has passed, should be good to go!

**Review by tnull — APPROVED** [review]

**Pull request merged**
